### ISSUE TITLE
关于https://blog.siaimes.me/2022/05/30/p62.html有些错误的地方

### ISSUE THREAD

**Issue by ben0i0d** [siaimes/k8s-share#1]
那个docker镜像里的cali那个的checksum对不上，我进入docker container手动下了官方GitHub的release
否则就会报错，不能匹配
另外，docker里的那个hi*的tag不对，你的hub里是0521，但是教程是0524.
此外 ，安装驱动直接用drivers common更轻松一点

**Comment by siaimes** [comment]
> 那个docker镜像里的cali那个的checksum对不上，我进入docker container手动下了官方GitHub的release 否则就会报错，不能匹配 另外，docker里的那个hi*的tag不对，你的hub里是0521，但是教程是0524. 此外 ，安装驱动直接用drivers common更轻松一点

1. 没理解；
2. 已修复；
3. 您喜欢就好。

**Comment by ben0i0d** [comment]
那我来详细说明第一点，第一点发生在kubespray脚本，在从share容器下载calicoctl-linux-amd64（3.7.3）和cni-plugins-linux-amd64-v0.8.1.tgz时会提示校验和错误，解决方法是进入容器wget手动下载GitHub上文件。
我看了dockerfile，对应文件也是这样处理的，那就可能需要重新打包一个docker image
另外，我的搭建环境是Ubuntu 20.04

**Comment by siaimes** [comment]
这样的吗？我测试过没有问题的，而且也有其他人反馈通过这个k8s-share的方案安装成功了，没有遇到您说的问题。等我有空再测试看看。会不会是20.04的问题，我只测试了18.04。

**Comment by ben0i0d** [comment]
有这个可能！谢谢啦！

**Comment by siaimes** [comment]
@Ben-DA Thank you for your feedback, the issue has been fixed.
